const AERP_VERSION = '3.0.0';

const AERP_SPREADSHEET_ID = '15UtZ1jlm04fdzWXorkKEOy3ClwUbfid_BDw9wAh_lwU';

const AERP_SHEETS = {
  CORE_TABLAS: 'CORE_TABLAS',
  CORE_COLUMNAS: 'CORE_COLUMNAS',
  CORE_RELACIONES: 'CORE_RELACIONES',
  CORE_VISTAS: 'CORE_VISTAS',
  GEN_REGLAS: 'GEN_REGLAS',
  GEN_ACCIONES: 'GEN_ACCIONES',
  GEN_LOG: 'GEN_LOG',
  CAT_ESTADOS: 'CAT_ESTADOS'
};

const AERP_DEFAULTS = {
  VERSION: '1.0.0',
  TIPO_DATO: 'Text',
  TIPO_CONTROL: 'Text',
  CATEGORIA: 'Negocio'
};